### ISSUE TITLE
Comments on Chapter 5: Análisis espacial II: modelos econométricos espaciales

### ISSUE THREAD

**Issue by hernandezcortes** [jaime-pru/Analisis-de-datos-espaciales#12]
1. Line 3: “Mencionamos dos razones por las que” instead of “Mencionamos que dos son las razones por las que”.

2. Line 4: “fenómeno de interés no se” instead of “fenómeno de interes de no se”

3. I think that there is a big jump between chapter 4 and chapter 5. It might be good to remind the reader how regression analysis inform the concepts in this chapter. 

4. Perhaps it would be good to explain nested models a bit more so that the reader understand its use and relevance.

5. The methodology to estimate the spatial econometric model could be explained a bit better. I suggest the author to add a few sentences on how to perform steps i) to iv), particularly steps ii), iii), and iv).

6. It would be nice to add a bit of intuition about the differences between modelos de rezago and modelos de error. Is there a way to judge this analytically or is this theory-driven?

**Comment by jaime-pru** [comment]
Este capítulo fue reestructurado de forma considerable, gracias a las observaciones de las revisoras, por lo que se añadieron secciones, se ampliaron otras y en general se modificó la exposición.

Se recordó en una introducción añadida qué es lo que se pretende con el análisis de regresión y cómo se busca, a través de la econometría espacial, atender la violación a uno de los supuestos del modelo lineal. 

Se definió con cuidado el concepto de econometría espacial y se expuso cada uno de los efectos espaciales que integra el modelo general.  Además, se desglosó con más detalle el proceso para la estimación de los modelos espaciales, siguiendo las recomendaciones dadas, dividiendo por pasos. Por otro lado, se abundó sobre la interpretación de los dos modelos desarrollados.

Finalmente, se añadió una sección final donde se busca hacer una recapitulación de los contenidos tratados en el libro y se enlistan recomendaciones de lectura adicional.
