### ISSUE TITLE
Capítulo 2. Mapas coropléticos (...) / Chapter 2  [in Spanish] // JOSE Review

### ISSUE THREAD

**Issue by nmorandeira** [jaime-pru/Analisis-de-datos-espaciales#5]
_[ES] Este _issue_ se vincula a la revisión del artículo para la revista [JOSE Review](https://github.com/openjournals/jose-reviews/issues/173#event-6459353208)
[EN] This issue is linked to the [JOSE Review](https://github.com/openjournals/jose-reviews/issues/173#event-6459353208)_

Las siguientes son recomendaciones para el Capítulo 2:

- **¿Cuentas  con permiso para reproducir el texto de Coursera? “What is data”.** Por favor chequear la licencia del curso. En caso de estar permitida la reproducción, citar la fuente en el bookdown (no sólo en el pdf). Recordar también que un html es más accesible que un pdf para personas que usan lectores de pantalla.

- Considero que una referencia que no puede faltar en un curso de datos espaciales en castellano es el libro de Víctor Olaya. Creo que es el mejor material teórico sobre SIG. Encima está escrito en castellano por un español y es un libro libre :) https://volaya.github.io/libro-sig/ 

- Se introduce el término “georreferenciada” sin explicarlo ni definirlo. Resulta un concepto sumamente importante para el curso. 

- **Deben revisarse las definiciones de datos vectoriales y ráster.** 

En cuanto a _datos vectoriales_, la actual redacción parece decir que se usan puntos, líneas y polígonos en un mismo objeto espacial, cuando en verdad estos tipos de representaciones no pueden mezclarse en un mismo vectorial. 

En cuanto a los _datos ráster,_ la definición es incorrecta: no necesariamente los ráster provienen de imágenes tomadas por instrumentos ópticos; también pueden ser originadas por otros instrumentos (instrumentos satelitales de microondas activas o pasivas, por ejemplo); pero más generalmente un ráster puede ser una grilla que no derive de ningún instrumento sino que sea generada por un usuario, ya sea definiendo celdas y sus valores manualmente o a través de un modelo; también se pueden derivar rásters de otros rásters por álgebra de mapas. En el libro de Olaya se definen muy bien los modelos de representación vectoriales y ráster https://volaya.github.io/libro-sig/chapters/Tipos_datos.html

- Se menciona que los vectoriales de tipo SHP fueron desarrollados por ESRI. Si bien es correcto que esta empresa creó el formato, la frase es confusa ya que puede darse a entender que todos los archivos SHP son desarrollados por ESRI, incluso los que se usan en el curso.

- Explicaría la importancia del archivo .prj. Además, al descargar el shapefile del ejemplo hay un .prj. ¿Cómo se espera que un estudiante responda a la pregunta _Para qué sirven esos archivos_?

- _sf_: la explicación del paquete no es muy pertinente para un público novato que no conoce qué es GDAL, GEOS y PROJ. Mejor diría que es un paquete útil para manejar datos espaciales de tipo vectorial. En general, me parece mejor que uses tus propios términos para hablar del paquete, en lugar de reproducir lo que dice la ayuda (mismo ejemplo para tmap).

- Sección 2.4. Definir “mapa coroplético” (está en el título del capítulo y de la sección; y luego se habla de “mapa temático”, que tampoco se define).

- Sección 2.5. Paleta de colores. Sugiero incluir una mención sobre cuándo usar una escala divergente y cuándo no; también sugiero incluir una mención a la accesibilidad en cuanto al uso de colores apropiados para personas daltónicas o con ceguera de color. El capítulo 5 del libro de Víctor Olaya sobre visualización es muy interesante para sumar como bibliografía de esta sección. Por ejemplo, en esta sección versa sobre escalas divergentes y no divergentes: https://volaya.github.io/libro-sig/chapters/Mapas.html

- Sección 2.6. Para que la leyenda de los mapas quede en castellano, sugiero indicar cómo cambiar los nombres de las categorías (en particular para que diga “0 a 5” en vez de “0 to 5”).

- Nuevamente es decisión del autor, pero sugiero agregar también “entusiastas programadoras”. Justo en ese ejemplo parece que sólo los hombres desarrollan para R.

**Errores ortotipográficos:**
- “básicas de los datos y los datos espaciales” (sobra un “los”).
- “Instagram” (en un link).
- “[Maps in R](https://www.jstatsoft.org/article/view/v084i06) ([Tennekes 2018](https://jaime-pru.github.io/Analisis-de-datos-espaciales/references.html#ref-Tennekes2018))” (falta un espacio antes de la cita)
- “uno para la clase final, es decir a manera de anclas.” (se lee raro el “es decir” al final). 
- “tú mismo profundices” (falta tilde en tú)

**Comment by hernandezcortes** [comment]
1. Change “apuntamos” to “señalamos”.

2. Raster data need not to come from satellite images, it can come from other sources.

3. Not all spatial data have a time component, for example shapefiles might not necessarily have a  time component. Perhaps clarify that raster data has three components whereas other spatial data might only have location and attributes.

4. Line 22: Change “El material aquí desarrollado se sirve de información espacial de tipo vectorial”. To “El material presentado utiliza información espacial de tipo vectorial”.

5. Line 92: “De la mañana de información”. This sentence is not clear.

6. It would be good to explain what coordinate systems and projections are. This chapter goes over st_crs without a lot of detail and I have found this to be an important aspect of any data analysis. Please add a couple of lines explaining what a coordinate system is, why it is important to have spatial data in the same coordinate system and how it might be possible to change it. This would allow the readers to understand the importance of coordinate systems and how they play an important role while plotting maps.

7. Explain in which circumstances it is useful to calculate the centroids and how it might be used in the future.

8. Subsection “Mapa de percentiles”: It would be helpful to explain why the user might want to plot percentiles map and why it is a nice way of plotting the data.

**Comment by jaime-pru** [comment]
Correcciones hechas al Capítulo 2:


- Se prefirió cambiar la referencia al material licenciado y, en su lugar, se proporcionó un vínculo a otro material.
- Se incluyó de forma amplia las referencias al material de Víctor Olaya.
- Sobre el término “georreferenciada”, se trató de dar una definición que, aunque sucinta, recoge los elementos relevantes para el contenido que es expuesto. Además, se proporcionaron un par de ligas a materiales para abundar sobre el problema de la georreferencia.
- Para mejor definir los datos vectoriales y ráster, se toman algunos elementos de la definición de Olaya para tratar de resolver el error. Se remite a la estudiante al material recomendado.
- Sobre los datos vectoriales, se trató de mejorar la redacción para evitar la posible confusión entre el uso de las primitivas de líneas, puntos o polígonos.
- Sobre los datos raster, se toman algunos elementos de la definición de Olaya para tratar de resolver el error. Se remite a la estudiante al material recomendado.
- Sobre el desarrollo de ESRI de los SHP, se modificó la redacción de este párrafo para evitar la imprecisión señalada.
- Sobre el archivo .prj, En la nota al pie número 2 de este capítulo se señala los otros archivos, incluidos el PRJ.
- En la exposición del paquete sf, se simplificó su exposición y uso.
- En la definición de mapa coroplético, en efecto, había un error. Se buscó aclarar los términos y se remitió a la estudiante al libro recomendado.
- Sobre el uso de las paletas de colores, se amplió la información sobre tres tipos de paletas y se abundó sobre su posible uso. Se añadió también la referencia recomendada.
- Para que la leyenda de los mapas quede en castellano, se incluyó una breve explicación de cómo modificar dicho elemento.
- Se corrigió la redacción para usar un lenguaje no sexista.
- Se buscó corregir todos los errores tipográficos identificados.
