### ISSUE TITLE
Capítulo 5. Análisis espacial II / Chapter 5  [in Spanish] // JOSE Review

### ISSUE THREAD

**Issue by nmorandeira** [jaime-pru/Analisis-de-datos-espaciales#8]
_[ES] Este _issue_ se vincula a la revisión del artículo para la revista [JOSE Review](https://github.com/openjournals/jose-reviews/issues/173#event-6459353208)
[EN] This issue is linked to the [JOSE Review](https://github.com/openjournals/jose-reviews/issues/173#event-6459353208)_

Los siguientes son comentarios sobre el Capítulo 5.

- Este capítulo tiene una carga cognitiva más alta que los demás. Se avanza rápido en conceptos muy complejos, en particular en la introducción teórica. Sugiero narrar un poco más qué utilidad tiene cada modelo, explicar con más detenimiento las opciones de la Figura 5.1, explicar un poco las ecuaciones incluidas, etc. 

- No queda claro qué es el multiplicador de Lagrange (no se define ni se explica con detenimiento); por lo tanto tampoco queda claro qué son las versiones robustas de ese multiplicador.

- No queda claro por qué el modelo es “anidado”.

- Figura 5.1. Es ilegible. Texto borroso en baja resolución.

- Figuras 5.2 y 5.3. Son difíciles de leer, texto borroso y con sombreado.

- Cita Anselin y Rey. En algunos casos, no está linkeada a su referencia. Corregir apariciones de Ansuelin por Anselin.

- “hay que mirar los resultados de las versiones robustas para tomar la decisión final”, ¿por qué?

- Para mayor claridad, ¿es posible incluir gráficas que ayuden a interpretar el output de los modelos? (quizás no, pero noto contraste respecto a la interpretación de los capítulos anteriores). Se siente que el capítulo termina apresuradamente, quizás con más interpretación sobre el/los modelos seleccionados (ayudado o no con una gráfica) es posible comprender mejor los últimos resultados y quedarnos con una imagen más acabada del curso.

- No me queda claro si los modelos enseñados son específicamente econométricos. Parece ser que no, que son modelos espaciales aplicados a econometría, pero que podrían ser aplicados a otras disciplinas. Aclarar.

- Al final de este capítulo o en uno nuevo, sugiero incluir una sección con conclusiones, hilando los aportes de todo el curso, y otras aproximaciones que pueden tener lxs estudiantes si quisieran produndizar en sus análisis. Si bien esto está dicho en este capítulo, se siente que se acelera el fin del curso y sería bueno recapitular para el cierre con los aportes de cada capítulo.

**Errores orto-tipográficos**

- “es sintetizado por **nuestro autores**” (corregir, no sé a qué autores se refiere antes de ver el epígrafe).

- responder a la pregunta: “¿Los errores de nuestro modelo están correlacionados?” (agregar comillas o cursiva)

**Comment by jaime-pru** [comment]
Correcciones al Capítulo 5:

Este capítulo se modificó de forma considerable, tratando de atender a los comentarios de las revisoras. Gracias a sus críticas, me parece el capítulo ganó claridad y precisión. 

- Se escribió una explicación más detallada y más didáctica sobre el llamado modelo general.
- Del multiplicador de Lagrange, se trató de explicar, sin llegar a su formalización, en qué consiste el estadístico, usando algunas comparaciones.
- Del modelo es “anidado”, se trató de aclarar mejor el modelo y explicarlo con detalle.
- Se reeditaron las figuras 1, 2 y 3, con una mejor resolución.
- Se corrigió la cita de Anselin y Rey, no se colocó el link después de la primera mención.
- Sobre las versiones robustas del multiplicador de Lagrange, se trató de hacer una exposición más cuidadosa de la ruta de interpretación de los modelos con el uso de tales estadísticos.
- Sobre la decisión de los modelos, se hizo un esfuerzo por lograr una exposición más cuidadosa y guiada, se incluyó de forma explícita la secuencia que la estudiante debe seguir y se brindaron más ejemplos.
- Sobre los modelos econométricos, se trató de brindar una mejor exposición del tipo de modelos econométricos usados y se puntualizó la terminología en la sección aclarando que todo lo expuesto, en el capítulo 4 y 5, son modelos econométricos.
- Antes del final, se hace una recapitulación donde se usan herramientas de los capítulos previos, tratando de unir todos los elementos mínimos necesarios para una adecuada secuencia de interpretación.
- Se corrigieron los errores orto-tipográficos.
